### PR TITLE
Add `refactor-nrepl.find-symbol-test`

### PR DESCRIPTION
**Pull request by vemv**
Tries reproducing https://github.com/clojure-emacs/clj-refactor.el/issues/485

`find-symbol` seemed to lack test coverage anyway.

### CODE REVIEW

**Comment by expez** [comment]
> `find-symbol` seemed to lack test coverage anyway.

We have a lot of various integration tests for this op in the `refactor-nrepl.integration-tests` ns.  That ns runs through the entire middleware, by sending messages like `clj-refactor` would and complements the more targeted unit tests.

**Comment by vemv** [comment]
Right, I was grepping for `find-symbol` instead of `find-usages`. Thanks!

I'll see if I can repro https://github.com/clojure-emacs/clj-refactor.el/issues/485 by also hacking `refactor-nrepl.integration-tests`.

**Comment by vemv** [comment]
The second commit managed to break the build in a pretty wild way, which is both good and bad news 🙃

**Comment by vemv** [comment]
After a few tweaks, the build is green again.

Finally, `(set! *warn-on-reflection* true)` wasn't causing a test failure whatsoever. It was other stuff failing.

Then how comes https://github.com/clojure-emacs/refactor-nrepl `master` is green?

I believe it's because of the `with_cache` CI step. Why are we caching `repo` again? https://github.com/clojure-emacs/refactor-nrepl/blob/392d41749a0771f4e32d53579932fa63b59c69c0/.circleci/config.yml#L85

Seems really an odd thing to do. It plausibly is caching mranderson's work i.e. the `target` dir, so test results can get tainted.

**Comment by bbatsov** [comment]
Yeah, caching the repo seems pretty weird.

**Comment by vemv** [comment]
PR ready again, and green

The summary is:

* Add `refactor-nrepl.find-symbol-test`
  * Tries reproducing https://github.com/clojure-emacs/clj-refactor.el/issues/485
  * I did not accomplish reproducing any problem. Still it seems useful to have this increased test coverage.
* Add a `testing`
  * The related deftest was failing too opaquely (when failing)
* Fix `set-refresh-dirs`
  * Fixes an issue masked by a prior problem in CI.
* Make `read-ns-form` handle invalid files
  * Fixes an issue masked by a prior probem in CI.
* Remove repo caching
  * This appears to cache mranderson's work, which is plausibly problematic across CI jobs.

**Review by bbatsov — APPROVED** [review]
LGTM

**Pull request merged**
