### PR TITLE
#217 NullPointerException in refactor-nrepl.core/build-artifact? fixed

### PR DESCRIPTION
**Pull request by mbuczko**
fixes NPE when a deps.edn based project is loaded.

### CODE REVIEW

**Comment by expez** [comment]
I don't mean to discourage your efforts by saying this, but getting a NPE here is the right thing.  

Calling a function that expects a `path-or-a-file` with `nil` indicates a problem elsewhere in the code.  I'd rather treat the disease than a specific symptom.

**Comment by mbuczko** [comment]
Sure, thanks for commenting this out. I will try to dig a bit deeper to see where the actual problem is.

**Comment by mbuczko** [comment]
@expez  you were right. Looks like it's rather the problem of `refactor-nrepl.core/project-root` which does not take _deps.edn_ into consideration as a project root. When added to the `names-at-root`, no additional checks for nil-ed `path-or-a-file` is required.

I'm closing this issue and PR and moving conversation to the new one :)

**Comment by expez** [comment]
Good stuff! :+1:

**Pull request closed without merging**
