### PR TITLE
Latest deps

### PR DESCRIPTION
**Pull request by dotemacs**
Upgraded Clojure 1.9.0-xyz to the latest 1.9.0 release.

Checklist
-------

- [x] The commits are consistent with our [contribution guidelines](CONTRIBUTING.md)
- [x] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (run `lein do clean, test`)
- [x] Code inlining with mranderson works and tests pass with inlined code (run `./build.sh install` -- takes a long time)

### CODE REVIEW

**Comment by dotemacs** [comment]
1/3 test runs fails.

The test with `openjdk7` is the culprit:

https://travis-ci.org/clojure-emacs/refactor-nrepl/jobs/313733211

**Comment by dotemacs** [comment]
Also, noticed that TravisCI supports `oraclejdk9` as one of the build JDKs. 
Should I add it to .travisci ?

**Comment by dotemacs** [comment]
In the previous push, I upgraded Clojure 1.9.0-alpha17 -> 1.9.0 and ClojureScript 1.9.671 -> 1.9.946, which caused the build failure with openjdk7, with this exception:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CompilerOptions : Unsupported major.minor version 52.0, compiling:(cljs/externs.clj:1:1)
```

Reverted back the ClojureScript upgrade and the tests passed.

**Comment by benedekfazekas** [comment]
ta! will have a look

**Comment by dotemacs** [comment]
Adding oraclejdk9 to .travisci results in the following failure:
https://travis-ci.org/clojure-emacs/refactor-nrepl/jobs/313884026

```
Exception in thread "main" java.lang.ClassNotFoundException: sun.misc.Launcher, compiling:(mranderson048/alembic/v0v3v2/dynapath/v0v2v3/dynapath/defaults.clj:29:3)
```

Which is related to this classloader issue https://github.com/tobias/clojure-java-9/issues/3

**Comment by dotemacs** [comment]
I'll remove the addition of `oraclejdk9` from **.travisci**.

I'll just try to see how much upward movement I can get by upgrading ClojureScript from the current **1.9.671** as there are the following releases since:

- 1.9.854
- 1.9.908
- 1.9.946

**Comment by dotemacs** [comment]
Upgraded ClojureScript to **1.9.854**, the tests passed.

Will try the next release...

**Comment by dotemacs** [comment]
With ClojureScript **1.9.908** the tests pass:

https://travis-ci.org/clojure-emacs/refactor-nrepl/builds/314065470

But with the latest ClojureScript release **1.9.946**, as shown above:

https://github.com/clojure-emacs/refactor-nrepl/commit/5f16bc5ce3941b188f81aec65717c5fc9e50cb60

the tests fail:

https://travis-ci.org/clojure-emacs/refactor-nrepl/jobs/313733211

What would you like to do?

**Comment by benedekfazekas** [comment]
just went with cljs that works. ta!

**Pull request merged**
