### PR TITLE
Tidy up2

### PR DESCRIPTION
**Pull request by luxbock**
Sorry about using a second pull request instead of just pushing into the previous branch, but I had to battle for a while with git to get everything to work and this just seemed simpler. I think I changed all of your suggestions and reverted some of the other changes that were clearly causing problems. I hope it's all good now.

### CODE REVIEW

**Comment by benedekfazekas** [comment]
cheers, will have a look on the whole diff for the PR

**Comment by benedekfazekas** [comment]
happy with this. can you pls squash the commits so i can merge. ta!

**Comment by luxbock** [comment]
Does this look ok?

**Comment by benedekfazekas** [comment]
awesome. ta!

**Pull request merged**
